# golangci-lint configuration for Wichita Radar
# https://golangci-lint.run/usage/configuration/

run:
  # Timeout for analysis
  timeout: 5m

  # Include test files
  tests: true

  # Go version to target
  go: '1.21'

linters:
  enable:
    # Enabled by default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code and reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused code

    # Additional recommended linters
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import statements are formatted according to the 'goimport' command
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go (drop-in replacement of golint)
    - gosec         # Inspects source code for security problems
    - unconvert     # Remove unnecessary type conversions
    - bodyclose     # Check whether HTTP response body is closed successfully
    - sqlclosecheck # Check that sql.Rows and sql.Stmt are closed
    - errname       # Check that sentinel errors are prefixed with Err and error types are suffixed with Error
    - errorlint     # Find code that will cause problems with the error wrapping scheme introduced in Go 1.13
    - gocyclo       # Computes and checks the cyclomatic complexity of functions
    - whitespace    # Detection of leading and trailing whitespace

  disable:
    - typecheck     # Disabled because it can conflict with build tags
    - godot         # Don't require periods at end of comments
    - gocritic      # Overly opinionated, can be noisy
    - noctx         # Overly strict about http context usage
    - unparam       # Noisy about function parameters

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`
    check-type-assertions: true
    # Report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`
    check-blank: false

  govet:
    # Enable all analyzers
    enable-all: true
    # Disable shadow variable checking (can be overly strict)
    disable:
      - shadow
      - fieldalignment  # Struct field alignment is micro-optimization, not critical

  gocyclo:
    # Minimal code complexity to report
    min-complexity: 15

  misspell:
    locale: US

  revive:
    # Enable pragmatic rules, disable overly strict style rules
    enable-all-rules: false
    rules:
      # Disable strict style rules
      - name: exported
        disabled: true  # Don't require comments on all exported items
      - name: package-comments
        disabled: true  # Don't require package comment
      - name: var-naming
        disabled: true  # Don't enforce strict variable naming (imageUrl vs imageURL)
      - name: unused-parameter
        disabled: true  # Allow unused parameters (common in tests)

      # Keep important logic/error rules
      - name: indent-error-flow
        disabled: false
      - name: blank-imports
        disabled: false
      - name: dot-imports
        disabled: false
      - name: error-return
        disabled: false
      - name: error-strings
        disabled: false
      - name: error-naming
        disabled: false
      - name: var-declaration
        disabled: false
      - name: unreachable-code
        disabled: false
      - name: redefines-builtin-id
        disabled: false

  gosec:
    # Exclude specific rules (G104 is about unhandled errors, we use errcheck for that)
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
      - G107  # HTTP requests with variables (common in web apps)
      - G114  # HTTP server without timeouts (production uses reverse proxy)
      - G301  # Directory permissions (0755 is standard for cache/log dirs)
      - G304  # File path from variable (sanitized via filepath package)

issues:
  # Exclude some linters from running on tests files
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - unparam

    # Exclude known false positives
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude shadow checking in tests
    - path: _test\.go
      text: "shadow"
      linters:
        - govet

    # Allow unused types in test files (test helpers, mocks)
    - path: _test\.go
      linters:
        - unused

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show all issues
  exclude-use-default: false
