services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "316:316"
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    environment:
      - PORT=316
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: modd

volumes:
  go-modules:
