version: "3.8"
services:
  php:
    hostname: www
    domainname: wichitaradar.local
    image: auchri/docker-apache-php
    container_name: wichitaradar
    ports:
      - "316:80"
    volumes:
      - .:/var/www/html/
