services:
  php:
    hostname: www
    domainname: wichitaradar.local
    image: auchri/docker-apache-php
    container_name: wichitaradar
    ports:
      - "316:80"
      - "443:443"
    volumes:
      - .:/var/www/html/
    command: >
      bash -c "mkdir -p /var/www/html/scraped/xml &&
               chown -R www-data:www-data /var/www/html/scraped &&
               chmod -R 777 /var/www/html/scraped &&
               apache2ctl -D FOREGROUND"

# to visit site: https://localhost:316