services:
  - type: web
    name: wichitaradar
    env: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app cmd/server/main.go
    startCommand: ./app
    plan: free
    autoDeploy: true
    branch: main