name: Update Year

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight UTC daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-year:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Update year in LICENSE
        run: |
          YEAR=$(date +%Y)
          sed -i "s/Copyright (c) [0-9]\{4\}/Copyright (c) ${YEAR}/" LICENSE

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add LICENSE
          git diff --quiet && git diff --staged --quiet || git commit -m "Update copyright year to ${YEAR}"
          git push